export const degreeCatalog = [
  { major: "Engineering", degree: "B.Tech Computer Science Engineering" },
  { major: "Engineering", degree: "B.Tech Artificial Intelligence" },
  { major: "Engineering", degree: "B.Tech Artificial Intelligence and Machine Learning" },
  { major: "Engineering", degree: "B.Tech Data Science" },
  { major: "Engineering", degree: "B.Tech Information Technology" },
  { major: "Engineering", degree: "B.Tech Software Engineering" },
  { major: "Engineering", degree: "B.Tech Cyber Security" },
  { major: "Engineering", degree: "B.Tech Blockchain Technology" },
  { major: "Engineering", degree: "B.Tech Civil Engineering" },
  { major: "Engineering", degree: "B.Tech Mechanical Engineering" },
  { major: "Engineering", degree: "B.Tech Electrical Engineering" },
  { major: "Engineering", degree: "B.Tech Electronics and Communication Engineering" },
  { major: "Engineering", degree: "B.Tech Aerospace Engineering" },
  { major: "Engineering", degree: "B.Tech Automobile Engineering" },
  { major: "Engineering", degree: "B.Tech Mechatronics Engineering" },
  { major: "Engineering", degree: "B.Tech Robotics Engineering" },
  { major: "Engineering", degree: "B.Tech Chemical Engineering" },
  { major: "Engineering", degree: "B.Tech Petroleum Engineering" },
  { major: "Engineering", degree: "B.Tech Marine Engineering" },
  { major: "Engineering", degree: "B.Tech Mining Engineering" },
  { major: "Engineering", degree: "M.Tech Computer Science Engineering" },
  { major: "Engineering", degree: "M.Tech Artificial Intelligence" },
  { major: "Engineering", degree: "M.Tech Data Science" },
  { major: "Engineering", degree: "M.Tech Civil Engineering" },
  { major: "Engineering", degree: "M.Tech Mechanical Engineering" },
  { major: "Computer and IT", degree: "BCA" },
  { major: "Computer and IT", degree: "MCA" },
  { major: "Computer and IT", degree: "B.Sc Computer Science" },
  { major: "Computer and IT", degree: "B.Sc Data Science" },
  { major: "Computer and IT", degree: "B.Sc Artificial Intelligence" },
  { major: "Computer and IT", degree: "B.Sc Cyber Security" },
  { major: "Computer and IT", degree: "B.Sc Information Technology" },
  { major: "Computer and IT", degree: "PG Diploma Data Science" },
  { major: "Computer and IT", degree: "PG Diploma Artificial Intelligence" },
  { major: "Computer and IT", degree: "PG Diploma Cyber Security" },
  { major: "Medical", degree: "MBBS" },
  { major: "Medical", degree: "MD General Medicine" },
  { major: "Medical", degree: "MS General Surgery" },
  { major: "Medical", degree: "DM Cardiology" },
  { major: "Medical", degree: "MCh Neurosurgery" },
  { major: "Dental", degree: "BDS" },
  { major: "Dental", degree: "MDS Orthodontics" },
  { major: "Dental", degree: "MDS Prosthodontics" },
  { major: "Dental", degree: "MDS Oral Surgery" },
  { major: "Pharmacy", degree: "B.Pharm" },
  { major: "Pharmacy", degree: "D.Pharm" },
  { major: "Pharmacy", degree: "Pharm.D" },
  { major: "Pharmacy", degree: "M.Pharm Pharmacology" },
  { major: "Pharmacy", degree: "M.Pharm Pharmaceutics" },
  { major: "Nursing", degree: "B.Sc Nursing" },
  { major: "Nursing", degree: "Post Basic B.Sc Nursing" },
  { major: "Nursing", degree: "M.Sc Nursing" },
  { major: "Nursing", degree: "Diploma General Nursing and Midwifery" },
  { major: "Commerce", degree: "B.Com" },
  { major: "Commerce", degree: "B.Com Honours" },
  { major: "Commerce", degree: "B.Com Accounting" },
  { major: "Commerce", degree: "B.Com Finance" },
  { major: "Commerce", degree: "M.Com" },
  { major: "Commerce", degree: "M.Com Finance" },
  { major: "Business and Management", degree: "BBA" },
  { major: "Business and Management", degree: "BBA Finance" },
  { major: "Business and Management", degree: "BBA Marketing" },
  { major: "Business and Management", degree: "BBA Human Resource" },
  { major: "Business and Management", degree: "MBA" },
  { major: "Business and Management", degree: "MBA Finance" },
  { major: "Business and Management", degree: "MBA Marketing" },
  { major: "Business and Management", degree: "MBA Human Resource" },
  { major: "Business and Management", degree: "MBA Operations" },
  { major: "Business and Management", degree: "PGDM" },
  { major: "Arts", degree: "BA English" },
  { major: "Arts", degree: "BA History" },
  { major: "Arts", degree: "BA Political Science" },
  { major: "Arts", degree: "BA Sociology" },
  { major: "Arts", degree: "BA Philosophy" },
  { major: "Arts", degree: "MA English" },
  { major: "Arts", degree: "MA History" },
  { major: "Arts", degree: "MA Political Science" },
  { major: "Arts", degree: "MA Sociology" },
  { major: "Science", degree: "B.Sc Physics" },
  { major: "Science", degree: "B.Sc Chemistry" },
  { major: "Science", degree: "B.Sc Mathematics" },
  { major: "Science", degree: "B.Sc Biology" },
  { major: "Science", degree: "M.Sc Physics" },
  { major: "Science", degree: "M.Sc Chemistry" },
  { major: "Science", degree: "M.Sc Mathematics" },
  { major: "Science", degree: "M.Sc Biotechnology" },
  { major: "Law", degree: "LLB" },
  { major: "Law", degree: "BA LLB" },
  { major: "Law", degree: "BBA LLB" },
  { major: "Law", degree: "B.Com LLB" },
  { major: "Law", degree: "LLM Constitutional Law" },
  { major: "Law", degree: "LLM Corporate Law" },
  { major: "Design", degree: "B.Des" },
  { major: "Design", degree: "M.Des" },
  { major: "Design", degree: "Fashion Design" },
  { major: "Design", degree: "Interior Design" },
  { major: "Design", degree: "Product Design" },
  { major: "Hotel Management", degree: "BHM" },
  { major: "Hotel Management", degree: "B.Sc Hotel Management" },
  { major: "Hotel Management", degree: "Diploma Hotel Management" },
  { major: "Hotel Management", degree: "MBA Hospitality Management" },
  { major: "Tourism", degree: "Bachelor Tourism Studies" },
  { major: "Tourism", degree: "BA Travel and Tourism" },
  { major: "Tourism", degree: "MBA Tourism Management" },
  { major: "Architecture", degree: "B.Arch" },
  { major: "Architecture", degree: "M.Arch Urban Design" },
  { major: "Architecture", degree: "M.Arch Landscape Architecture" }
] as const;

export const majorOptions = [...new Set(degreeCatalog.map((item) => item.major)), "Other"];

export const academicYearOptions = [
  "1st Year",
  "2nd Year",
  "3rd Year",
  "4th Year",
  "5th Year",
  "Undergraduate",
  "Postgraduate",
  "Doctoral",
  "Other"
];

export const semesterOptions = [
  "Semester 1",
  "Semester 2",
  "Semester 3",
  "Semester 4",
  "Semester 5",
  "Semester 6",
  "Semester 7",
  "Semester 8",
  "Semester 9",
  "Semester 10",
  "Trimester 1",
  "Trimester 2",
  "Trimester 3",
  "Other"
];

export const interests = [
  "📚 Studying",
  "🎵 Music",
  "🏃 Running",
  "🎮 Gaming",
  "🍕 Foodie",
  "✈️ Travel",
  "🎨 Art",
  "🏀 Sports",
  "🎭 Theater",
  "💻 Tech",
  "🌿 Nature",
  "📸 Photography",
  "🎸 Guitar",
  "🏋️ Fitness",
  "📖 Reading",
  "🎬 Movies",
  "🧪 Science",
  "🌍 Languages",
  "🤝 Volunteering"
];

export const groups = [
  { id: "1", name: "CS Study Squad", members: 342, emoji: "💻" },
  { id: "2", name: "Foodies on Campus", members: 218, emoji: "🍕" },
  { id: "3", name: "Music Collective", members: 156, emoji: "🎵" }
];
